import {
  Banknote,
  Cake,
  CalendarCheck,
  CalendarClock,
  Coins,
  PaintRoller,
  PawPrint,
  PlugZap,
  Sigma,
  GraduationCap,
  HeartPulse,
  House,
  Landmark,
  Percent,
  PiggyBank,
  Receipt,
  SquareSigma,
  Tag,
  Trophy,
  Wallet,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const calculatorTools: ToolMeta[] = [
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    category: "calculators",
    description: "Work out percentages, increases, decreases and 'what percent of'.",
    keywords: [
      "percentage calculator",
      "percent of a number",
      "percentage increase",
      "percentage difference",
      "how to calculate percentage",
    ],
    icon: Percent,
    related: ["discount-calculator", "grade-calculator", "tax-calculator", "attendance-calculator"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    category: "calculators",
    description: "Find an exact age in years, months, days — and the next birthday.",
    keywords: ["age calculator", "how old am i", "date of birth calculator", "age in days"],
    icon: Cake,
    related: ["time-converter", "percentage-calculator", "attendance-calculator", "bmi-calculator"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "gpa-calculator",
    name: "GPA Calculator",
    category: "calculators",
    description: "Add your courses and credits to get a weighted grade point average.",
    keywords: ["gpa calculator", "grade point average", "college gpa", "semester gpa"],
    icon: GraduationCap,
    related: ["cgpa-calculator", "grade-calculator", "percentage-calculator", "attendance-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "cgpa-calculator",
    name: "CGPA Calculator",
    category: "calculators",
    description: "Combine several semesters into one cumulative grade average.",
    keywords: ["cgpa calculator", "cumulative gpa", "overall gpa", "cgpa to percentage"],
    icon: Trophy,
    related: ["gpa-calculator", "grade-calculator", "percentage-calculator", "attendance-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "grade-calculator",
    name: "Grade Calculator",
    category: "calculators",
    description: "Turn marks into a percentage and a letter grade.",
    keywords: ["grade calculator", "marks to percentage", "test score calculator", "letter grade"],
    icon: SquareSigma,
    related: ["gpa-calculator", "cgpa-calculator", "percentage-calculator", "attendance-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "attendance-calculator",
    name: "Attendance Calculator",
    category: "calculators",
    description: "See your attendance percentage and how many classes you still need.",
    keywords: [
      "attendance calculator",
      "attendance percentage",
      "how many classes can i miss",
      "75 percent attendance",
    ],
    icon: CalendarCheck,
    related: ["percentage-calculator", "grade-calculator", "gpa-calculator", "age-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "emi-calculator",
    name: "EMI Calculator",
    category: "calculators",
    description: "Monthly instalment, total interest and a full repayment schedule.",
    keywords: ["emi calculator", "equated monthly instalment", "loan emi", "monthly payment"],
    icon: Banknote,
    related: ["loan-calculator", "mortgage-calculator", "compound-interest-calculator", "salary-calculator"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    category: "calculators",
    description: "Compare loan amounts, rates and terms with an amortisation table.",
    keywords: ["loan calculator", "personal loan", "car loan calculator", "interest calculator"],
    icon: Landmark,
    related: ["emi-calculator", "mortgage-calculator", "compound-interest-calculator", "tax-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    category: "calculators",
    description: "Home price, deposit, taxes and insurance in one monthly figure.",
    keywords: ["mortgage calculator", "home loan calculator", "monthly mortgage payment", "piti"],
    icon: House,
    related: ["loan-calculator", "emi-calculator", "compound-interest-calculator", "tax-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "compound-interest-calculator",
    name: "Compound Interest Calculator",
    category: "calculators",
    description: "Project savings growth with regular contributions.",
    keywords: [
      "compound interest calculator",
      "investment growth",
      "savings calculator",
      "future value",
    ],
    icon: PiggyBank,
    related: ["loan-calculator", "emi-calculator", "salary-calculator", "percentage-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    category: "calculators",
    description: "Body mass index in metric or imperial, with the healthy weight range.",
    keywords: ["bmi calculator", "body mass index", "healthy weight", "bmi chart"],
    icon: HeartPulse,
    related: ["weight-converter", "length-converter", "age-calculator", "percentage-calculator"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    category: "calculators",
    description: "Sale price, money saved, and stacked or reverse discounts.",
    keywords: ["discount calculator", "sale price calculator", "percent off", "how much did i save"],
    icon: Tag,
    related: ["percentage-calculator", "tax-calculator", "currency-converter", "salary-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "tax-calculator",
    name: "Tax Calculator",
    category: "calculators",
    description: "Add or remove sales tax, VAT or GST from any amount.",
    keywords: ["tax calculator", "vat calculator", "gst calculator", "sales tax", "add tax to price"],
    icon: Receipt,
    related: ["discount-calculator", "percentage-calculator", "invoice-generator", "salary-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "salary-calculator",
    name: "Salary Calculator",
    category: "calculators",
    description: "Convert between hourly, weekly, monthly and yearly pay.",
    keywords: ["salary calculator", "hourly to annual", "pay converter", "annual salary"],
    icon: Wallet,
    related: ["tax-calculator", "emi-calculator", "compound-interest-calculator", "currency-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    category: "calculators",
    description: "Trigonometry, logs, powers and parentheses with a full history.",
    keywords: ["scientific calculator", "online calculator", "trigonometry calculator", "log calculator"],
    icon: Sigma,
    related: ["percentage-calculator", "grade-calculator", "compound-interest-calculator", "length-converter"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "paint-coverage-calculator",
    name: "Paint and Wallpaper Calculator",
    category: "calculators",
    description: "Work out how much paint or wallpaper a room needs, down to the tins to buy.",
    keywords: [
      "how much paint do i need calculator",
      "paint calculator",
      "wallpaper calculator",
      "paint coverage calculator",
      "how many rolls of wallpaper",
    ],
    icon: PaintRoller,
    related: ["area-converter", "length-converter", "volume-converter", "discount-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "pet-age-calculator",
    name: "Pet Age Calculator",
    category: "calculators",
    description: "Convert a dog's or cat's age to human years, adjusted for size and breed.",
    keywords: [
      "dog age in human years calculator",
      "dog years calculator",
      "cat age in human years",
      "pet age calculator",
      "how old is my dog in human years",
    ],
    icon: PawPrint,
    related: ["age-calculator", "bmi-calculator", "weight-converter", "time-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "take-home-pay-calculator",
    name: "Take-Home Pay Calculator",
    category: "calculators",
    description: "See salary after tax for the UK, Canada, Australia or India, with every deduction.",
    keywords: [
      "uk take home pay calculator",
      "salary after tax calculator",
      "net pay calculator",
      "income tax calculator 2026",
      "take home salary india",
    ],
    icon: Coins,
    related: ["salary-calculator", "tax-calculator", "percentage-calculator", "subscription-cost-tracker"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "ev-charging-cost-calculator",
    name: "EV Charging Cost Calculator",
    category: "calculators",
    description: "Work out what charging an electric car costs, per charge, per mile or per km.",
    keywords: [
      "ev charging cost calculator",
      "electric car charging cost",
      "cost to charge a tesla",
      "ev vs petrol cost",
      "kwh cost per mile",
    ],
    icon: PlugZap,
    related: ["engine-cc-to-hp", "speed-converter", "percentage-calculator", "subscription-cost-tracker"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "subscription-cost-tracker",
    name: "Subscription Cost Tracker",
    category: "calculators",
    description: "List your subscriptions to see the real monthly and yearly cost, then print it.",
    keywords: [
      "subscription cost calculator",
      "subscription tracker",
      "monthly subscriptions total",
      "how much do i spend on subscriptions",
      "printable subscription list",
    ],
    icon: CalendarClock,
    related: ["take-home-pay-calculator", "percentage-calculator", "discount-calculator", "currency-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
];
