import {
  Box,
  Coins,
  Gauge,
  HardDrive,
  Ruler,
  Square,
  Thermometer,
  Timer,
  Weight,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const converterTools: ToolMeta[] = [
  {
    slug: "currency-converter",
    name: "Currency Converter",
    category: "converters",
    description: "Convert between 30+ currencies using daily reference rates.",
    keywords: ["currency converter", "exchange rate", "usd to eur", "money converter", "forex rates"],
    icon: Coins,
    related: ["salary-calculator", "discount-calculator", "tax-calculator", "data-storage-converter"],
    requiresFile: false,
    processing: "client-with-lookup",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "length-converter",
    name: "Length Converter",
    category: "converters",
    description: "Metres, feet, inches, miles and eleven other length units.",
    keywords: ["length converter", "cm to inches", "feet to metres", "km to miles", "distance converter"],
    icon: Ruler,
    related: ["weight-converter", "area-converter", "volume-converter", "speed-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "weight-converter",
    name: "Weight Converter",
    category: "converters",
    description: "Kilograms, pounds, stones, ounces and grams.",
    keywords: ["weight converter", "kg to lbs", "pounds to kg", "stone to kg", "mass converter"],
    icon: Weight,
    related: ["length-converter", "bmi-calculator", "volume-converter", "area-converter"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "temperature-converter",
    name: "Temperature Converter",
    category: "converters",
    description: "Celsius, Fahrenheit, Kelvin and Rankine, side by side.",
    keywords: ["temperature converter", "celsius to fahrenheit", "c to f", "kelvin converter"],
    icon: Thermometer,
    related: ["length-converter", "weight-converter", "speed-converter", "volume-converter"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "time-converter",
    name: "Time Converter",
    category: "converters",
    description: "Seconds to years, and everything in between.",
    keywords: ["time converter", "hours to minutes", "days to hours", "seconds converter"],
    icon: Timer,
    related: ["timestamp-converter", "age-calculator", "speed-converter", "length-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "speed-converter",
    name: "Speed Converter",
    category: "converters",
    description: "km/h, mph, knots, m/s and the speed of sound.",
    keywords: ["speed converter", "kmh to mph", "mph to kmh", "knots to mph", "velocity converter"],
    icon: Gauge,
    related: ["length-converter", "time-converter", "temperature-converter", "weight-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "area-converter",
    name: "Area Converter",
    category: "converters",
    description: "Square metres, acres, hectares, square feet and more.",
    keywords: ["area converter", "square feet to square metres", "acres to hectares", "land area"],
    icon: Square,
    related: ["length-converter", "volume-converter", "weight-converter", "mortgage-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "volume-converter",
    name: "Volume Converter",
    category: "converters",
    description: "Litres, gallons, cups and spoons — US and imperial kept apart.",
    keywords: ["volume converter", "litres to gallons", "ml to cups", "cooking measurements"],
    icon: Box,
    related: ["weight-converter", "area-converter", "length-converter", "temperature-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "data-storage-converter",
    name: "Data Storage Converter",
    category: "converters",
    description: "Bytes to terabytes, with decimal and binary units separated.",
    keywords: ["data storage converter", "mb to gb", "gib vs gb", "bytes converter", "file size"],
    icon: HardDrive,
    related: ["time-converter", "compress-image", "compress-pdf", "base64-encoder"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
];
