import {
  Binary,
  Braces,
  CheckCheck,
  Clock,
  Code2,
  Fingerprint,
  KeyRound,
  MailCheck,
  Share2,
  ShieldCheck,
  Link2,
  Palette,
  Table2,
  Unlink,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const developerTools: ToolMeta[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    category: "developer",
    description: "Pretty-print or minify JSON, with the exact error position.",
    keywords: ["json formatter", "json beautifier", "pretty print json", "json pretty", "format json online"],
    icon: Braces,
    related: ["json-validator", "json-to-csv", "base64-encoder", "html-formatter"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "json-validator",
    name: "JSON Validator",
    category: "developer",
    description: "Check JSON syntax and get a plain-English explanation of errors.",
    keywords: ["json validator", "validate json", "json syntax checker", "is my json valid"],
    icon: CheckCheck,
    related: ["json-formatter", "json-to-csv", "html-formatter", "css-formatter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "json-to-csv",
    name: "JSON to CSV",
    category: "developer",
    description: "Flatten nested JSON into a spreadsheet-ready CSV.",
    keywords: ["json to csv", "convert json to excel", "json to spreadsheet", "flatten json"],
    icon: Table2,
    related: ["json-formatter", "json-validator", "pdf-to-excel", "base64-encoder"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder",
    category: "developer",
    description: "Encode text or a file to Base64, standard or URL-safe.",
    keywords: ["base64 encoder", "encode base64", "text to base64", "file to base64", "data uri"],
    icon: Binary,
    related: ["base64-decoder", "url-encoder", "json-formatter", "uuid-generator"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "base64-decoder",
    name: "Base64 Decoder",
    category: "developer",
    description: "Decode Base64 back to text or download it as a file.",
    keywords: ["base64 decoder", "decode base64", "base64 to text", "base64 to file"],
    icon: Binary,
    related: ["base64-encoder", "url-decoder", "json-formatter", "timestamp-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "url-encoder",
    name: "URL Encoder",
    category: "developer",
    description: "Percent-encode a whole URL or a single query parameter.",
    keywords: ["url encoder", "percent encoding", "encode uri", "escape url", "query string encoder"],
    icon: Link2,
    related: ["url-decoder", "base64-encoder", "json-formatter", "qr-code-generator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "url-decoder",
    name: "URL Decoder",
    category: "developer",
    description: "Decode percent-encoded URLs and break out query parameters.",
    keywords: ["url decoder", "decode url", "unescape url", "percent decode", "parse query string"],
    icon: Unlink,
    related: ["url-encoder", "base64-decoder", "json-formatter", "timestamp-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "html-formatter",
    name: "HTML Formatter",
    category: "developer",
    description: "Indent messy HTML, or minify it for production.",
    keywords: ["html formatter", "html beautifier", "format html", "html minifier", "indent html"],
    icon: Code2,
    related: ["css-formatter", "json-formatter", "url-encoder", "json-validator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "css-formatter",
    name: "CSS Formatter",
    category: "developer",
    description: "Beautify or minify stylesheets, including nested rules.",
    keywords: ["css formatter", "css beautifier", "format css", "css minifier", "tidy css"],
    icon: Palette,
    related: ["html-formatter", "json-formatter", "json-validator", "base64-encoder"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "timestamp-converter",
    name: "Timestamp Converter",
    category: "developer",
    description: "Unix time to a readable date, in UTC and your local zone.",
    keywords: ["timestamp converter", "unix timestamp", "epoch converter", "epoch to date", "iso 8601"],
    icon: Clock,
    related: ["time-converter", "age-calculator", "uuid-generator", "json-formatter"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "checksum-verifier",
    name: "File Checksum Verifier",
    category: "developer",
    description: "Calculate MD5, SHA-1, SHA-256 or SHA-512 and compare with a published hash.",
    keywords: [
      "verify file checksum online",
      "sha256 checksum",
      "md5 checksum",
      "file hash calculator",
      "check file integrity",
    ],
    icon: Fingerprint,
    related: ["base64-encoder", "uuid-generator", "json-validator", "url-encoder"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "ssl-expiry-checker",
    name: "SSL Certificate Checker",
    category: "developer",
    description: "See when a domain's SSL certificate expires and whether its chain is trusted.",
    keywords: [
      "check ssl certificate expiry date",
      "ssl certificate checker",
      "ssl expiry checker",
      "tls certificate check",
      "certificate chain checker",
    ],
    icon: ShieldCheck,
    related: ["email-syntax-checker", "og-preview", "robots-txt-generator", "checksum-verifier"],
    requiresFile: false,
    processing: "server-lookup",
    addedOn: "2026-09-10",
  },
  {
    slug: "email-syntax-checker",
    name: "Email Address Validator",
    category: "developer",
    description: "Check email address format with plain-English errors, typo fixes and MX lookups.",
    keywords: [
      "check if email address is valid format",
      "email address validator",
      "email syntax checker",
      "mx record lookup",
      "verify email domain",
    ],
    icon: MailCheck,
    related: ["ssl-expiry-checker", "password-strength-checker", "og-preview", "url-encoder"],
    requiresFile: false,
    processing: "server-lookup",
    addedOn: "2026-09-10",
  },
  {
    slug: "password-strength-checker",
    name: "Password Strength Checker",
    category: "developer",
    description: "Estimate how long a password would take to crack, checked privately in your browser.",
    keywords: [
      "password strength checker",
      "how strong is my password",
      "password crack time",
      "password security test",
      "zxcvbn password checker",
    ],
    icon: KeyRound,
    related: ["password-generator", "checksum-verifier", "email-syntax-checker", "uuid-generator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "og-preview",
    name: "Open Graph Preview",
    category: "developer",
    description: "Preview how a link looks when shared, and check or write its Open Graph tags.",
    keywords: [
      "open graph preview tool",
      "og tags checker",
      "social share preview",
      "twitter card validator",
      "link preview generator",
    ],
    icon: Share2,
    related: ["robots-txt-generator", "favicon-generator", "ssl-expiry-checker", "html-formatter"],
    requiresFile: false,
    processing: "server-lookup",
    addedOn: "2026-09-10",
  },
];

