import {
  Barcode,
  Bot,
  Dices,
  FileJson,
  Fingerprint,
  KeyRound,
  Link,
  PenLine,
  QrCode,
  ReceiptText,
  UserRound,
  Wifi,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const generatorTools: ToolMeta[] = [
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    category: "generators",
    description: "QR codes for links, text, email, phone, SMS and Wi-Fi.",
    keywords: ["qr code generator", "make a qr code", "wifi qr code", "url to qr", "free qr code"],
    icon: QrCode,
    related: ["barcode-generator", "uuid-generator", "password-generator", "url-encoder"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "barcode-generator",
    name: "Barcode Generator",
    category: "generators",
    description: "CODE128, EAN-13, UPC-A and other retail barcode formats.",
    keywords: ["barcode generator", "ean 13 generator", "code128", "upc barcode", "product barcode"],
    icon: Barcode,
    related: ["qr-code-generator", "invoice-generator", "uuid-generator", "random-number-generator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    category: "generators",
    description: "Strong random passwords and passphrases with a strength estimate.",
    keywords: ["password generator", "strong password", "random password", "secure password maker"],
    icon: KeyRound,
    related: ["uuid-generator", "random-number-generator", "qr-code-generator", "base64-encoder"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "random-number-generator",
    name: "Random Number Generator",
    category: "generators",
    description: "Pick numbers in a range, with or without repeats.",
    keywords: ["random number generator", "pick a random number", "lottery numbers", "dice roller"],
    icon: Dices,
    related: ["password-generator", "uuid-generator", "lorem-ipsum-generator", "scientific-calculator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    category: "generators",
    description: "Build a professional invoice and export it as a real PDF.",
    keywords: ["invoice generator", "free invoice template", "create invoice pdf", "billing"],
    icon: ReceiptText,
    related: ["resume-generator", "tax-calculator", "currency-converter", "barcode-generator"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "resume-generator",
    name: "Resume Generator",
    category: "generators",
    description: "Fill in your details and download a clean one-page CV.",
    keywords: ["resume generator", "cv builder", "free resume maker", "resume pdf", "curriculum vitae"],
    icon: UserRound,
    related: ["invoice-generator", "word-counter", "text-cleaner", "word-to-pdf"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    category: "generators",
    description: "Placeholder copy by paragraph, sentence, word or list.",
    keywords: ["lorem ipsum generator", "dummy text", "placeholder text", "filler text"],
    icon: PenLine,
    related: ["word-counter", "random-number-generator", "character-counter", "case-converter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    category: "generators",
    description: "Version 4 and version 7 UUIDs, plus NIL and ULID-style output.",
    keywords: ["uuid generator", "guid generator", "uuid v4", "uuid v7", "random id"],
    icon: Fingerprint,
    related: ["password-generator", "random-number-generator", "timestamp-converter", "base64-encoder"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator and Tester",
    category: "generators",
    description: "Build a robots.txt file and test which URLs each crawler may fetch.",
    keywords: [
      "robots.txt generator",
      "robots.txt tester",
      "block ai crawlers robots.txt",
      "robots txt checker",
      "disallow googlebot",
    ],
    icon: Bot,
    related: ["og-preview", "ssl-expiry-checker", "favicon-generator", "url-encoder"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "schema-generator",
    name: "Schema Markup Generator",
    category: "generators",
    description: "Create FAQ and Product JSON-LD structured data, checked against Google's rules.",
    keywords: [
      "faq schema generator",
      "product schema generator",
      "json-ld generator",
      "structured data generator",
      "faqpage schema markup",
    ],
    icon: FileJson,
    related: ["og-preview", "robots-txt-generator", "utm-builder", "json-formatter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "utm-builder",
    name: "UTM Link Builder",
    category: "generators",
    description: "Build campaign links with UTM tags, keep a history and download QR codes.",
    keywords: ["utm link builder", "utm builder", "campaign url builder", "google analytics utm", "utm qr code"],
    icon: Link,
    related: ["qr-code-generator", "og-preview", "url-encoder", "schema-generator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "qr-code-wifi-vcard",
    name: "Wi-Fi and vCard QR Code Generator",
    category: "generators",
    description: "Make QR codes for Wi-Fi, contact cards, menus and events, with printable cards.",
    keywords: [
      "wifi qr code generator",
      "vcard qr code generator",
      "menu qr code",
      "event qr code",
      "printable wifi qr card",
    ],
    icon: Wifi,
    related: ["qr-code-generator", "utm-builder", "barcode-generator", "favicon-generator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
];
