import {
  Crop,
  FileImage,
  Images,
  Repeat2,
  RotateCw,
  ScanText,
  Shrink,
  Smartphone,
  Scaling,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const imageTools: ToolMeta[] = [
  {
    slug: "compress-image",
    name: "Compress Image",
    category: "image",
    description: "Cut image file size with a live before-and-after preview.",
    keywords: ["compress image", "reduce image size", "image compressor", "optimise photo", "shrink jpg"],
    icon: Shrink,
    related: ["resize-image", "image-converter", "png-to-jpg", "compress-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    category: "image",
    description: "Change dimensions by pixels or percentage, aspect ratio locked.",
    keywords: ["resize image", "change image dimensions", "scale photo", "image resizer"],
    icon: Scaling,
    related: ["compress-image", "crop-image", "image-converter", "rotate-image"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    category: "image",
    description: "Convert JPG photos to lossless PNG files.",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png"],
    icon: Repeat2,
    related: ["png-to-jpg", "image-converter", "webp-to-jpg", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    category: "image",
    description: "Convert PNG to JPG with a background colour for transparency.",
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg", "remove png transparency"],
    icon: Repeat2,
    related: ["jpg-to-png", "image-converter", "compress-image", "webp-to-jpg"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    category: "image",
    description: "Turn WebP images into JPGs that any app can open.",
    keywords: ["webp to jpg", "webp to jpeg", "convert webp", "open webp file"],
    icon: Repeat2,
    related: ["jpg-to-png", "png-to-jpg", "image-converter", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    category: "image",
    description: "Convert iPhone HEIC photos into universally readable JPGs.",
    keywords: ["heic to jpg", "heic to jpeg", "iphone photo converter", "open heic on windows"],
    icon: Smartphone,
    related: ["image-converter", "compress-image", "png-to-jpg", "image-to-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "image-to-text",
    name: "Image to Text (OCR)",
    category: "image",
    description: "Read the words out of a screenshot or photo of a document.",
    keywords: ["image to text", "ocr online", "extract text from image", "picture to text", "screenshot to text"],
    icon: ScanText,
    related: ["pdf-to-text", "word-counter", "image-to-pdf", "text-cleaner"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    category: "image",
    description: "Combine any mix of images into one PDF document.",
    keywords: ["image to pdf", "photo to pdf", "png to pdf", "pictures to pdf"],
    icon: FileImage,
    related: ["jpg-to-pdf", "merge-pdf", "compress-pdf", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    category: "image",
    description: "Drag out a crop area or snap to a preset aspect ratio.",
    keywords: ["crop image", "cut photo", "trim image", "crop to square", "image cropper"],
    icon: Crop,
    related: ["resize-image", "rotate-image", "compress-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "rotate-image",
    name: "Rotate Image",
    category: "image",
    description: "Rotate in 90° steps or flip horizontally and vertically.",
    keywords: ["rotate image", "flip image", "turn photo", "mirror image"],
    icon: RotateCw,
    related: ["crop-image", "resize-image", "rotate-pdf", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    category: "image",
    description: "Convert between JPG, PNG and WebP in a single batch.",
    keywords: ["image converter", "convert image format", "batch image convert", "change image type"],
    icon: Images,
    related: ["compress-image", "jpg-to-png", "png-to-jpg", "webp-to-jpg"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
];
