import {
  AppWindow,
  Crop,
  EyeOff,
  FileImage,
  Pipette,
  Images,
  Repeat2,
  RotateCw,
  ScanText,
  Shrink,
  Smartphone,
  Scaling,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const imageTools: ToolMeta[] = [
  {
    slug: "compress-image",
    name: "Compress Image",
    category: "image",
    description: "Cut image file size with a live before-and-after preview.",
    keywords: ["compress image", "reduce image size", "image compressor", "optimise photo", "shrink jpg"],
    icon: Shrink,
    related: ["resize-image", "image-converter", "png-to-jpg", "compress-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    category: "image",
    description: "Change dimensions by pixels or percentage, aspect ratio locked.",
    keywords: ["resize image", "change image dimensions", "scale photo", "image resizer"],
    icon: Scaling,
    related: ["compress-image", "crop-image", "image-converter", "rotate-image"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    category: "image",
    description: "Convert JPG photos to lossless PNG files.",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png"],
    icon: Repeat2,
    related: ["png-to-jpg", "image-converter", "webp-to-jpg", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    category: "image",
    description: "Convert PNG to JPG with a background colour for transparency.",
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg", "remove png transparency"],
    icon: Repeat2,
    related: ["jpg-to-png", "image-converter", "compress-image", "webp-to-jpg"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    category: "image",
    description: "Turn WebP images into JPGs that any app can open.",
    keywords: ["webp to jpg", "webp to jpeg", "convert webp", "open webp file"],
    icon: Repeat2,
    related: ["jpg-to-png", "png-to-jpg", "image-converter", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    category: "image",
    description: "Convert iPhone HEIC photos into universally readable JPGs.",
    keywords: [
      "heic to jpg converter online",
      "heic to jpg",
      "heic to jpeg",
      "batch heic converter",
      "iphone photo converter",
      "open heic on windows",
    ],
    icon: Smartphone,
    related: ["image-converter", "compress-image", "png-to-jpg", "image-to-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "image-to-text",
    name: "Image to Text (OCR)",
    category: "image",
    description: "Read the words out of a screenshot or photo of a document.",
    keywords: ["image to text", "ocr online", "extract text from image", "picture to text", "screenshot to text"],
    icon: ScanText,
    related: ["pdf-to-text", "word-counter", "image-to-pdf", "text-cleaner"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    category: "image",
    description: "Combine any mix of images into one PDF document.",
    keywords: ["image to pdf", "photo to pdf", "png to pdf", "pictures to pdf"],
    icon: FileImage,
    related: ["jpg-to-pdf", "merge-pdf", "compress-pdf", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    category: "image",
    description: "Drag out a crop area or snap to a preset aspect ratio.",
    keywords: ["crop image", "cut photo", "trim image", "crop to square", "image cropper"],
    icon: Crop,
    related: ["resize-image", "rotate-image", "compress-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "rotate-image",
    name: "Rotate Image",
    category: "image",
    description: "Rotate in 90° steps or flip horizontally and vertically.",
    keywords: ["rotate image", "flip image", "turn photo", "mirror image"],
    icon: RotateCw,
    related: ["crop-image", "resize-image", "rotate-pdf", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    category: "image",
    description: "Convert between JPG, PNG and WebP in a single batch.",
    keywords: ["image converter", "convert image format", "batch image convert", "change image type"],
    icon: Images,
    related: ["compress-image", "jpg-to-png", "png-to-jpg", "webp-to-jpg"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "webp-to-png",
    name: "WebP to PNG",
    category: "image",
    description: "Convert WebP images to PNG with transparency kept, or to JPG.",
    keywords: ["webp to png converter", "webp to png", "convert webp to png", "webp to jpg", "save webp as png"],
    icon: Repeat2,
    related: ["webp-to-jpg", "avif-to-jpg", "image-converter", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "avif-to-jpg",
    name: "AVIF to JPG",
    category: "image",
    description: "Convert AVIF images to JPG or PNG that older apps can open.",
    keywords: ["avif to jpg", "avif to jpeg", "avif to png", "convert avif", "open avif file"],
    icon: Repeat2,
    related: ["webp-to-png", "heic-to-jpg", "image-converter", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "image-color-palette",
    name: "Color Palette Extractor",
    category: "image",
    description: "Pull the dominant colours out of any image as HEX, RGB and HSL.",
    keywords: [
      "extract colors from image online",
      "color palette from image",
      "image color picker",
      "dominant colors",
      "hex color from image",
    ],
    icon: Pipette,
    related: ["favicon-generator", "compress-image", "crop-image", "css-formatter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "exif-remover",
    name: "EXIF Viewer and Remover",
    category: "image",
    description: "See the hidden camera and GPS data in a photo, then strip it out.",
    keywords: [
      "remove exif data from photo online",
      "exif remover",
      "exif viewer",
      "remove gps location from photo",
      "strip image metadata",
    ],
    icon: EyeOff,
    related: ["compress-image", "heic-to-jpg", "resize-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    category: "image",
    description: "Make favicon.ico, Apple touch and Android icons from an image or letter.",
    keywords: [
      "favicon generator",
      "favicon ico generator",
      "create favicon from image",
      "apple touch icon generator",
      "web manifest icons",
    ],
    icon: AppWindow,
    related: ["resize-image", "image-color-palette", "crop-image", "qr-code-generator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
];
