import {
  Aperture,
  AppWindow,
  Circle,
  Contrast,
  Crop,
  Droplets,
  EyeOff,
  FileImage,
  Focus,
  Glasses,
  Images,
  Frame,
  Pipette,
  Printer,
  Repeat2,
  RotateCw,
  Scaling,
  ScanText,
  Shapes,
  Shrink,
  Smartphone,
  SquareUser,
  Clapperboard,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const imageTools: ToolMeta[] = [
  {
    slug: "compress-image",
    name: "Compress Image",
    category: "image",
    description: "Cut image file size with a live before-and-after preview.",
    keywords: ["compress image", "reduce image size", "image compressor", "optimise photo", "shrink jpg"],
    icon: Shrink,
    related: ["resize-image", "image-converter", "png-to-jpg", "compress-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    category: "image",
    description: "Change dimensions by pixels or percentage, aspect ratio locked.",
    keywords: ["resize image", "change image dimensions", "scale photo", "image resizer"],
    icon: Scaling,
    related: ["compress-image", "crop-image", "image-converter", "rotate-image"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG",
    category: "image",
    description: "Convert JPG photos to lossless PNG files.",
    keywords: ["jpg to png", "jpeg to png", "convert jpg to png"],
    icon: Repeat2,
    related: ["png-to-jpg", "image-converter", "webp-to-jpg", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "png-to-jpg",
    name: "PNG to JPG",
    category: "image",
    description: "Convert PNG to JPG with a background colour for transparency.",
    keywords: ["png to jpg", "png to jpeg", "convert png to jpg", "remove png transparency"],
    icon: Repeat2,
    related: ["jpg-to-png", "image-converter", "compress-image", "webp-to-jpg"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "webp-to-jpg",
    name: "WebP to JPG",
    category: "image",
    description: "Turn WebP images into JPGs that any app can open.",
    keywords: ["webp to jpg", "webp to jpeg", "convert webp", "open webp file"],
    icon: Repeat2,
    related: ["jpg-to-png", "png-to-jpg", "image-converter", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "heic-to-jpg",
    name: "HEIC to JPG",
    category: "image",
    description: "Convert iPhone HEIC photos into universally readable JPGs.",
    keywords: [
      "heic to jpg converter online",
      "heic to jpg",
      "heic to jpeg",
      "batch heic converter",
      "iphone photo converter",
      "open heic on windows",
    ],
    icon: Smartphone,
    related: ["image-converter", "compress-image", "png-to-jpg", "image-to-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "image-to-text",
    name: "Image to Text (OCR)",
    category: "image",
    description: "Read the words out of a screenshot or photo of a document.",
    keywords: ["image to text", "ocr online", "extract text from image", "picture to text", "screenshot to text"],
    icon: ScanText,
    related: ["pdf-to-text", "word-counter", "image-to-pdf", "text-cleaner"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "image-to-pdf",
    name: "Image to PDF",
    category: "image",
    description: "Combine any mix of images into one PDF document.",
    keywords: ["image to pdf", "photo to pdf", "png to pdf", "pictures to pdf"],
    icon: FileImage,
    related: ["jpg-to-pdf", "merge-pdf", "compress-pdf", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    category: "image",
    description: "Drag out a crop area or snap to a preset aspect ratio.",
    keywords: ["crop image", "cut photo", "trim image", "crop to square", "image cropper"],
    icon: Crop,
    related: ["resize-image", "rotate-image", "compress-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "rotate-image",
    name: "Rotate Image",
    category: "image",
    description: "Rotate in 90° steps or flip horizontally and vertically.",
    keywords: ["rotate image", "flip image", "turn photo", "mirror image"],
    icon: RotateCw,
    related: ["crop-image", "resize-image", "rotate-pdf", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "image-converter",
    name: "Image Converter",
    category: "image",
    description: "Convert between JPG, PNG and WebP in a single batch.",
    keywords: ["image converter", "convert image format", "batch image convert", "change image type"],
    icon: Images,
    related: ["compress-image", "jpg-to-png", "png-to-jpg", "webp-to-jpg"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "webp-to-png",
    name: "WebP to PNG",
    category: "image",
    description: "Convert WebP images to PNG with transparency kept, or to JPG.",
    keywords: ["webp to png converter", "webp to png", "convert webp to png", "webp to jpg", "save webp as png"],
    icon: Repeat2,
    related: ["webp-to-jpg", "avif-to-jpg", "image-converter", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "avif-to-jpg",
    name: "AVIF to JPG",
    category: "image",
    description: "Convert AVIF images to JPG or PNG that older apps can open.",
    keywords: ["avif to jpg", "avif to jpeg", "avif to png", "convert avif", "open avif file"],
    icon: Repeat2,
    related: ["webp-to-png", "heic-to-jpg", "image-converter", "compress-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "image-color-palette",
    name: "Color Palette Extractor",
    category: "image",
    description: "Pull the dominant colours out of any image as HEX, RGB and HSL.",
    keywords: [
      "extract colors from image online",
      "color palette from image",
      "image color picker",
      "dominant colors",
      "hex color from image",
    ],
    icon: Pipette,
    related: ["favicon-generator", "compress-image", "crop-image", "css-formatter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "exif-remover",
    name: "EXIF Viewer and Remover",
    category: "image",
    description: "See the hidden camera and GPS data in a photo, then strip it out.",
    keywords: [
      "remove exif data from photo online",
      "exif remover",
      "exif viewer",
      "remove gps location from photo",
      "strip image metadata",
    ],
    icon: EyeOff,
    related: ["compress-image", "heic-to-jpg", "resize-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    category: "image",
    description: "Make favicon.ico, Apple touch and Android icons from an image or letter.",
    keywords: [
      "favicon generator",
      "favicon ico generator",
      "create favicon from image",
      "apple touch icon generator",
      "web manifest icons",
    ],
    icon: AppWindow,
    related: ["resize-image", "image-color-palette", "crop-image", "qr-code-generator"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "png-to-webp",
    name: "PNG to WebP Converter",
    category: "image",
    description: "Shrink PNGs for the web while keeping transparency.",
    keywords: [
      "png to webp converter",
      "convert png to webp",
      "png to webp online",
      "webp converter free",
      "compress png to webp",
    ],
    icon: FileImage,
    related: ["webp-to-png", "jpg-to-webp", "compress-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "jpg-to-webp",
    name: "JPG to WebP Converter",
    category: "image",
    description: "Convert photos to WebP, typically a third smaller.",
    keywords: [
      "jpg to webp converter",
      "jpeg to webp",
      "convert jpg to webp",
      "webp image converter",
      "photo to webp",
    ],
    icon: Images,
    related: ["png-to-webp", "webp-to-jpg", "compress-image", "jpg-to-avif"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "jpg-to-avif",
    name: "JPG to AVIF Converter",
    category: "image",
    description: "Encode photos as AVIF, the smallest widely supported format.",
    keywords: [
      "jpg to avif converter",
      "convert jpg to avif",
      "avif converter online",
      "jpeg to avif",
      "make avif images",
    ],
    icon: Aperture,
    related: ["avif-to-jpg", "jpg-to-webp", "compress-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "svg-to-png",
    name: "SVG to PNG Converter",
    category: "image",
    description: "Render an SVG to a sharp PNG at any size you choose.",
    keywords: [
      "svg to png converter",
      "convert svg to png",
      "svg to png online",
      "rasterize svg",
      "export svg as png",
    ],
    icon: Shapes,
    related: ["png-to-webp", "favicon-generator", "image-converter", "resize-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "circle-crop-image",
    name: "Circle Crop Image",
    category: "image",
    description: "Cut a photo into a circle with a transparent background.",
    keywords: [
      "circle crop image online",
      "crop photo into circle",
      "round profile picture",
      "circular image cropper",
      "make image round",
    ],
    icon: Circle,
    related: ["crop-image", "resize-image", "instagram-image-resizer", "passport-photo-maker"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "passport-photo-maker",
    name: "Passport Photo Maker",
    category: "image",
    description: "Size a portrait to UK, US, EU, China or Australia rules.",
    keywords: [
      "passport photo size online",
      "passport photo maker",
      "35x45mm photo",
      "2x2 inch photo",
      "visa photo size",
    ],
    icon: SquareUser,
    related: ["circle-crop-image", "crop-image", "resize-image", "image-dpi-changer"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "instagram-image-resizer",
    name: "Instagram Image Resizer",
    category: "image",
    description: "Crop or pad a picture to every Instagram size.",
    keywords: [
      "instagram image size",
      "instagram photo resizer",
      "instagram post size",
      "reels size",
      "resize for instagram",
    ],
    icon: Frame,
    related: ["circle-crop-image", "resize-image", "crop-image", "image-watermark"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "youtube-thumbnail-downloader",
    name: "YouTube Thumbnail Grabber",
    category: "image",
    description: "Save any video's thumbnail at full resolution.",
    keywords: [
      "youtube thumbnail downloader",
      "download youtube thumbnail",
      "youtube thumbnail grabber",
      "get video thumbnail",
      "youtube thumbnail hd",
    ],
    icon: Clapperboard,
    related: ["image-converter", "resize-image", "compress-image", "image-color-palette"],
    requiresFile: false,
    processing: "client-with-lookup",
    addedOn: "2026-09-16",
  },
  {
    slug: "image-watermark",
    name: "Add Watermark to Image",
    category: "image",
    description: "Stamp your name across a photo before sharing it.",
    keywords: [
      "add watermark to image",
      "photo watermark online",
      "watermark picture free",
      "copyright photo",
      "watermark jpg",
    ],
    icon: Droplets,
    related: ["exif-remover", "blur-faces-in-photo", "resize-image", "instagram-image-resizer"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "blur-faces-in-photo",
    name: "Blur Faces in a Photo",
    category: "image",
    description: "Blur faces or number plates into the picture itself.",
    keywords: [
      "blur faces in photo online",
      "blur face free",
      "hide faces in picture",
      "blur number plate",
      "censor photo online",
    ],
    icon: Focus,
    related: ["exif-remover", "image-watermark", "crop-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "image-dpi-changer",
    name: "Change Image DPI",
    category: "image",
    description: "Set the print density, or resize for a physical width.",
    keywords: [
      "change dpi of image",
      "300 dpi converter",
      "image dpi changer",
      "set image resolution for print",
      "dpi calculator image",
    ],
    icon: Printer,
    related: ["resize-image", "passport-photo-maker", "compress-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "grayscale-image",
    name: "Black and White Image Converter",
    category: "image",
    description: "Convert a picture to grayscale three different ways.",
    keywords: [
      "convert image to black and white",
      "grayscale image online",
      "greyscale converter",
      "black and white photo converter",
      "remove colour from image",
    ],
    icon: Contrast,
    related: ["color-blindness-simulator", "image-color-palette", "compress-image", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
  {
    slug: "color-blindness-simulator",
    name: "Colour Blindness Simulator",
    category: "image",
    description: "See a design as the four main types of colour vision do.",
    keywords: [
      "color blindness simulator",
      "colour blind checker",
      "deuteranopia simulator",
      "accessibility color checker",
      "protanopia test image",
    ],
    icon: Glasses,
    related: ["grayscale-image", "image-color-palette", "exif-remover", "image-converter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-16",
  },
];
