import {
  Combine,
  FileArchive,
  FileCog,
  ListOrdered,
  Ruler,
  TableProperties,
  FileImage,
  FileSpreadsheet,
  FileText,
  FileType2,
  Images,
  RotateCw,
  Scissors,
  SquareSplitVertical,
  Trash2,
} from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const pdfTools: ToolMeta[] = [
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    category: "pdf",
    description: "Combine several PDFs into one file, in the order you choose.",
    keywords: ["merge pdf", "combine pdf", "join pdf", "pdf merger", "concatenate pdf"],
    icon: Combine,
    related: ["split-pdf", "extract-pdf-pages", "delete-pdf-pages", "compress-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    category: "pdf",
    description: "Break a PDF into separate files by page range or one file per page.",
    keywords: ["split pdf", "divide pdf", "separate pdf pages", "pdf splitter"],
    icon: Scissors,
    related: ["merge-pdf", "extract-pdf-pages", "delete-pdf-pages", "pdf-to-jpg"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    category: "pdf",
    description: "Shrink a PDF by re-encoding the images inside it.",
    keywords: ["compress pdf", "reduce pdf size", "shrink pdf", "pdf compressor"],
    icon: FileArchive,
    related: ["merge-pdf", "split-pdf", "pdf-to-jpg", "compress-image"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    category: "pdf",
    description: "Pull the text out of a PDF into an editable .docx document.",
    keywords: ["pdf to word", "pdf to docx", "convert pdf to word", "pdf to editable text"],
    icon: FileType2,
    related: ["word-to-pdf", "pdf-to-text", "pdf-to-excel", "merge-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    category: "pdf",
    description: "Turn a .docx document into a clean, shareable PDF.",
    keywords: ["word to pdf", "docx to pdf", "convert word document to pdf"],
    icon: FileText,
    related: ["pdf-to-word", "merge-pdf", "compress-pdf", "jpg-to-pdf"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    category: "pdf",
    description: "Render every page of a PDF as a JPG image.",
    keywords: ["pdf to jpg", "pdf to jpeg", "pdf to image", "convert pdf pages to images"],
    icon: FileImage,
    related: ["jpg-to-pdf", "pdf-to-png", "split-pdf", "compress-image"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    category: "pdf",
    description: "Put your photos into a single PDF, one image per page.",
    keywords: ["jpg to pdf", "jpeg to pdf", "images to pdf", "photo to pdf"],
    icon: Images,
    related: ["pdf-to-jpg", "image-to-pdf", "merge-pdf", "compress-pdf"],
    requiresFile: true,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "pdf-to-png",
    name: "PDF to PNG",
    category: "pdf",
    description: "Export PDF pages as lossless PNG images.",
    keywords: ["pdf to png", "pdf page to png", "pdf to transparent image"],
    icon: FileImage,
    related: ["pdf-to-jpg", "jpg-to-pdf", "png-to-jpg", "split-pdf"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "pdf-to-excel",
    name: "PDF to Excel",
    category: "pdf",
    description: "Recover tables from a PDF into an .xlsx spreadsheet.",
    keywords: ["pdf to excel", "pdf to xlsx", "pdf table to spreadsheet", "extract table from pdf"],
    icon: FileSpreadsheet,
    related: ["pdf-to-word", "pdf-to-text", "json-to-csv", "split-pdf"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    category: "pdf",
    description: "Extract the plain text from a PDF, page by page.",
    keywords: ["pdf to text", "extract text from pdf", "pdf to txt", "copy text from pdf"],
    icon: FileText,
    related: ["pdf-to-word", "pdf-to-excel", "image-to-text", "word-counter"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "rotate-pdf",
    name: "Rotate PDF",
    category: "pdf",
    description: "Turn sideways or upside-down pages the right way up.",
    keywords: ["rotate pdf", "turn pdf pages", "fix pdf orientation", "rotate pdf pages"],
    icon: RotateCw,
    related: ["merge-pdf", "split-pdf", "delete-pdf-pages", "rotate-image"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "delete-pdf-pages",
    name: "Delete PDF Pages",
    category: "pdf",
    description: "Remove the pages you do not need and keep the rest.",
    keywords: ["delete pdf pages", "remove pages from pdf", "erase pdf page"],
    icon: Trash2,
    related: ["extract-pdf-pages", "split-pdf", "merge-pdf", "rotate-pdf"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "extract-pdf-pages",
    name: "Extract PDF Pages",
    category: "pdf",
    description: "Pull selected pages out into a brand new PDF.",
    keywords: ["extract pdf pages", "get pages from pdf", "select pdf pages", "pdf page extractor"],
    icon: SquareSplitVertical,
    related: ["delete-pdf-pages", "split-pdf", "merge-pdf", "pdf-to-jpg"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "pdf-add-page-numbers",
    name: "Add Page Numbers to PDF",
    category: "pdf",
    description: "Number PDF pages in any corner, in the format and from the number you choose.",
    keywords: [
      "add page numbers to pdf online",
      "number pdf pages",
      "pdf page numbering",
      "insert page numbers pdf",
      "bates style page numbers",
    ],
    icon: ListOrdered,
    related: ["pdf-resize-page", "merge-pdf", "pdf-metadata-editor", "rotate-pdf"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "pdf-table-to-excel",
    name: "PDF Table Extractor",
    category: "pdf",
    description: "Pull a table that spans many PDF pages into one Excel or CSV sheet.",
    keywords: [
      "extract table from pdf to excel",
      "pdf table to csv",
      "multi page pdf table to excel",
      "copy table from pdf",
      "pdf table extractor",
    ],
    icon: TableProperties,
    related: ["pdf-to-excel", "pdf-to-text", "json-to-csv", "pdf-add-page-numbers"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "pdf-metadata-editor",
    name: "PDF Metadata Editor",
    category: "pdf",
    description: "Edit or clear a PDF's title, author, keywords, dates and producer.",
    keywords: [
      "edit pdf metadata online",
      "change pdf title",
      "remove pdf metadata",
      "pdf properties editor",
      "pdf author change",
    ],
    icon: FileCog,
    related: ["exif-remover", "compress-pdf", "pdf-add-page-numbers", "merge-pdf"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
  {
    slug: "pdf-resize-page",
    name: "PDF Page Size Converter",
    category: "pdf",
    description: "Convert PDF pages between A4, Letter, Legal, A3 and A5, scaled to fit.",
    keywords: [
      "convert pdf a4 to letter",
      "pdf letter to a4",
      "change pdf page size",
      "resize pdf pages",
      "pdf paper size converter",
    ],
    icon: Ruler,
    related: ["pdf-add-page-numbers", "compress-pdf", "rotate-pdf", "merge-pdf"],
    requiresFile: true,
    processing: "client",
    addedOn: "2026-09-10",
  },
];
