import { ArrowDownUp, CaseUpper, Eraser, FlipHorizontal, Hash, ListMinus, TextQuote } from "lucide-react";

import type { ToolMeta } from "@/types/tool";

export const textTools: ToolMeta[] = [
  {
    slug: "word-counter",
    name: "Word Counter",
    category: "text",
    description: "Live word, character, sentence and reading-time counts.",
    keywords: ["word counter", "count words", "essay word count", "character count", "reading time"],
    icon: TextQuote,
    related: ["character-counter", "case-converter", "text-cleaner", "lorem-ipsum-generator"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    category: "text",
    description: "Count characters against Twitter, SMS and meta-tag limits.",
    keywords: ["character counter", "count characters", "letter count", "sms character limit"],
    icon: Hash,
    related: ["word-counter", "text-cleaner", "case-converter", "sort-lines"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    category: "text",
    description: "UPPER, lower, Title, Sentence, camelCase, snake_case and more.",
    keywords: ["case converter", "uppercase to lowercase", "title case", "camelcase converter"],
    icon: CaseUpper,
    related: ["word-counter", "text-cleaner", "text-reverser", "sort-lines"],
    requiresFile: false,
    processing: "client",
    popular: true,
    addedOn: "2026-09-05",
  },
  {
    slug: "remove-duplicate-lines",
    name: "Remove Duplicate Lines",
    category: "text",
    description: "Strip repeated lines and see exactly how many were removed.",
    keywords: ["remove duplicate lines", "deduplicate text", "unique lines", "delete repeated lines"],
    icon: ListMinus,
    related: ["sort-lines", "text-cleaner", "word-counter", "json-formatter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "sort-lines",
    name: "Sort Lines",
    category: "text",
    description: "Alphabetical, numeric, length or random line ordering.",
    keywords: ["sort lines", "alphabetise list", "sort text", "order lines alphabetically"],
    icon: ArrowDownUp,
    related: ["remove-duplicate-lines", "text-cleaner", "case-converter", "word-counter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "text-reverser",
    name: "Text Reverser",
    category: "text",
    description: "Reverse characters, words or the order of the lines.",
    keywords: ["text reverser", "reverse text", "backwards text", "mirror words"],
    icon: FlipHorizontal,
    related: ["case-converter", "sort-lines", "text-cleaner", "character-counter"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
  {
    slug: "text-cleaner",
    name: "Text Cleaner",
    category: "text",
    description: "Fix smart quotes, stray spaces and broken line breaks.",
    keywords: ["text cleaner", "remove extra spaces", "strip formatting", "clean up text", "remove line breaks"],
    icon: Eraser,
    related: ["case-converter", "remove-duplicate-lines", "word-counter", "sort-lines"],
    requiresFile: false,
    processing: "client",
    addedOn: "2026-09-05",
  },
];
