"use client";

// Generated by scripts/generate-tool-map.mjs — do not edit by hand.
// Run `npm run generate:tools` after adding a tool to the registry.

import dynamic from "next/dynamic";
import type { ComponentType } from "react";

import { ToolSkeleton } from "@/components/tool/tool-frame";

const Loading = () => <ToolSkeleton />;

/**
 * Every tool is a separate lazily-loaded chunk, so visiting one tool page never
 * downloads the code for the other 87.
 */
const TOOL_COMPONENTS: Record<string, ComponentType> = {
  "merge-pdf": dynamic(() => import("./pdf/merge-pdf"), { loading: Loading }),
  "split-pdf": dynamic(() => import("./pdf/split-pdf"), { loading: Loading }),
  "compress-pdf": dynamic(() => import("./pdf/compress-pdf"), { loading: Loading }),
  "pdf-to-word": dynamic(() => import("./pdf/pdf-to-word"), { loading: Loading }),
  "word-to-pdf": dynamic(() => import("./pdf/word-to-pdf"), { loading: Loading }),
  "pdf-to-jpg": dynamic(() => import("./pdf/pdf-to-jpg"), { loading: Loading }),
  "jpg-to-pdf": dynamic(() => import("./pdf/jpg-to-pdf"), { loading: Loading }),
  "pdf-to-png": dynamic(() => import("./pdf/pdf-to-png"), { loading: Loading }),
  "pdf-to-excel": dynamic(() => import("./pdf/pdf-to-excel"), { loading: Loading }),
  "pdf-to-text": dynamic(() => import("./pdf/pdf-to-text"), { loading: Loading }),
  "rotate-pdf": dynamic(() => import("./pdf/rotate-pdf"), { loading: Loading }),
  "delete-pdf-pages": dynamic(() => import("./pdf/delete-pdf-pages"), { loading: Loading }),
  "extract-pdf-pages": dynamic(() => import("./pdf/extract-pdf-pages"), { loading: Loading }),
  "pdf-add-page-numbers": dynamic(() => import("./pdf/pdf-add-page-numbers"), { loading: Loading }),
  "pdf-table-to-excel": dynamic(() => import("./pdf/pdf-table-to-excel"), { loading: Loading }),
  "pdf-metadata-editor": dynamic(() => import("./pdf/pdf-metadata-editor"), { loading: Loading }),
  "pdf-resize-page": dynamic(() => import("./pdf/pdf-resize-page"), { loading: Loading }),
  "percentage-calculator": dynamic(() => import("./calculators/percentage-calculator"), { loading: Loading }),
  "age-calculator": dynamic(() => import("./calculators/age-calculator"), { loading: Loading }),
  "gpa-calculator": dynamic(() => import("./calculators/gpa-calculator"), { loading: Loading }),
  "cgpa-calculator": dynamic(() => import("./calculators/cgpa-calculator"), { loading: Loading }),
  "grade-calculator": dynamic(() => import("./calculators/grade-calculator"), { loading: Loading }),
  "attendance-calculator": dynamic(() => import("./calculators/attendance-calculator"), { loading: Loading }),
  "emi-calculator": dynamic(() => import("./calculators/emi-calculator"), { loading: Loading }),
  "loan-calculator": dynamic(() => import("./calculators/loan-calculator"), { loading: Loading }),
  "mortgage-calculator": dynamic(() => import("./calculators/mortgage-calculator"), { loading: Loading }),
  "compound-interest-calculator": dynamic(() => import("./calculators/compound-interest-calculator"), { loading: Loading }),
  "bmi-calculator": dynamic(() => import("./calculators/bmi-calculator"), { loading: Loading }),
  "discount-calculator": dynamic(() => import("./calculators/discount-calculator"), { loading: Loading }),
  "tax-calculator": dynamic(() => import("./calculators/tax-calculator"), { loading: Loading }),
  "salary-calculator": dynamic(() => import("./calculators/salary-calculator"), { loading: Loading }),
  "scientific-calculator": dynamic(() => import("./calculators/scientific-calculator"), { loading: Loading }),
  "compress-image": dynamic(() => import("./image/compress-image"), { loading: Loading }),
  "resize-image": dynamic(() => import("./image/resize-image"), { loading: Loading }),
  "jpg-to-png": dynamic(() => import("./image/jpg-to-png"), { loading: Loading }),
  "png-to-jpg": dynamic(() => import("./image/png-to-jpg"), { loading: Loading }),
  "webp-to-jpg": dynamic(() => import("./image/webp-to-jpg"), { loading: Loading }),
  "heic-to-jpg": dynamic(() => import("./image/heic-to-jpg"), { loading: Loading }),
  "image-to-text": dynamic(() => import("./image/image-to-text"), { loading: Loading }),
  "image-to-pdf": dynamic(() => import("./image/image-to-pdf"), { loading: Loading }),
  "crop-image": dynamic(() => import("./image/crop-image"), { loading: Loading }),
  "rotate-image": dynamic(() => import("./image/rotate-image"), { loading: Loading }),
  "image-converter": dynamic(() => import("./image/image-converter"), { loading: Loading }),
  "webp-to-png": dynamic(() => import("./image/webp-to-png"), { loading: Loading }),
  "avif-to-jpg": dynamic(() => import("./image/avif-to-jpg"), { loading: Loading }),
  "image-color-palette": dynamic(() => import("./image/image-color-palette"), { loading: Loading }),
  "exif-remover": dynamic(() => import("./image/exif-remover"), { loading: Loading }),
  "favicon-generator": dynamic(() => import("./image/favicon-generator"), { loading: Loading }),
  "currency-converter": dynamic(() => import("./converters/currency-converter"), { loading: Loading }),
  "length-converter": dynamic(() => import("./converters/length-converter"), { loading: Loading }),
  "weight-converter": dynamic(() => import("./converters/weight-converter"), { loading: Loading }),
  "temperature-converter": dynamic(() => import("./converters/temperature-converter"), { loading: Loading }),
  "time-converter": dynamic(() => import("./converters/time-converter"), { loading: Loading }),
  "speed-converter": dynamic(() => import("./converters/speed-converter"), { loading: Loading }),
  "area-converter": dynamic(() => import("./converters/area-converter"), { loading: Loading }),
  "volume-converter": dynamic(() => import("./converters/volume-converter"), { loading: Loading }),
  "data-storage-converter": dynamic(() => import("./converters/data-storage-converter"), { loading: Loading }),
  "qr-code-generator": dynamic(() => import("./generators/qr-code-generator"), { loading: Loading }),
  "barcode-generator": dynamic(() => import("./generators/barcode-generator"), { loading: Loading }),
  "password-generator": dynamic(() => import("./generators/password-generator"), { loading: Loading }),
  "random-number-generator": dynamic(() => import("./generators/random-number-generator"), { loading: Loading }),
  "invoice-generator": dynamic(() => import("./generators/invoice-generator"), { loading: Loading }),
  "resume-generator": dynamic(() => import("./generators/resume-generator"), { loading: Loading }),
  "lorem-ipsum-generator": dynamic(() => import("./generators/lorem-ipsum-generator"), { loading: Loading }),
  "uuid-generator": dynamic(() => import("./generators/uuid-generator"), { loading: Loading }),
  "robots-txt-generator": dynamic(() => import("./generators/robots-txt-generator"), { loading: Loading }),
  "word-counter": dynamic(() => import("./text/word-counter"), { loading: Loading }),
  "character-counter": dynamic(() => import("./text/character-counter"), { loading: Loading }),
  "case-converter": dynamic(() => import("./text/case-converter"), { loading: Loading }),
  "remove-duplicate-lines": dynamic(() => import("./text/remove-duplicate-lines"), { loading: Loading }),
  "sort-lines": dynamic(() => import("./text/sort-lines"), { loading: Loading }),
  "text-reverser": dynamic(() => import("./text/text-reverser"), { loading: Loading }),
  "text-cleaner": dynamic(() => import("./text/text-cleaner"), { loading: Loading }),
  "json-formatter": dynamic(() => import("./developer/json-formatter"), { loading: Loading }),
  "json-validator": dynamic(() => import("./developer/json-validator"), { loading: Loading }),
  "json-to-csv": dynamic(() => import("./developer/json-to-csv"), { loading: Loading }),
  "base64-encoder": dynamic(() => import("./developer/base64-encoder"), { loading: Loading }),
  "base64-decoder": dynamic(() => import("./developer/base64-decoder"), { loading: Loading }),
  "url-encoder": dynamic(() => import("./developer/url-encoder"), { loading: Loading }),
  "url-decoder": dynamic(() => import("./developer/url-decoder"), { loading: Loading }),
  "html-formatter": dynamic(() => import("./developer/html-formatter"), { loading: Loading }),
  "css-formatter": dynamic(() => import("./developer/css-formatter"), { loading: Loading }),
  "timestamp-converter": dynamic(() => import("./developer/timestamp-converter"), { loading: Loading }),
  "checksum-verifier": dynamic(() => import("./developer/checksum-verifier"), { loading: Loading }),
  "ssl-expiry-checker": dynamic(() => import("./developer/ssl-expiry-checker"), { loading: Loading }),
  "email-syntax-checker": dynamic(() => import("./developer/email-syntax-checker"), { loading: Loading }),
  "password-strength-checker": dynamic(() => import("./developer/password-strength-checker"), { loading: Loading }),
  "og-preview": dynamic(() => import("./developer/og-preview"), { loading: Loading }),
};

export function ToolMount({ slug }: { slug: string }) {
  const Component = TOOL_COMPONENTS[slug];
  if (!Component) return null;
  return <Component />;
}

export function hasToolComponent(slug: string): boolean {
  return slug in TOOL_COMPONENTS;
}
